import type { ChoiceQuestion, CodeChallengeData } from '../../types'

export const patternQuestions: ChoiceQuestion[] = [
  {
    id: 'two-pointers-pattern-1',
    prompt: 'Find two numbers in a sorted array whose sum equals a target.',
    choices: ['Two pointers', 'Hash map only', 'Stack', 'Prefix sum'],
    answer: 'Two pointers',
    signal: 'Sorted + pair + move inward',
    explanation: 'Start at the smallest and largest values. If the sum is too small, move left forward; if too large, move right backward.',
    tempting: 'A hash map can work, but sorted order gives enough information to solve it with O(1) extra space.',
  },
  {
    id: 'two-pointers-pattern-2',
    prompt: 'Check whether a string is a palindrome without building a reversed copy.',
    choices: ['Two pointers', 'Hash map', 'Queue', 'Binary search'],
    answer: 'Two pointers',
    signal: 'Compare mirrored positions',
    explanation: 'One pointer at each end compares corresponding characters and moves inward.',
  },
  {
    id: 'two-pointers-pattern-3',
    prompt: 'Remove duplicates from a sorted array while keeping one copy of each value.',
    choices: ['Fast/slow pointers', 'Stack', 'Prefix sum', 'Queue'],
    answer: 'Fast/slow pointers',
    signal: 'Sorted + compact valid values in place',
    explanation: 'One pointer scans; another marks where the next unique value belongs.',
  },
  {
    id: 'two-pointers-pattern-4',
    prompt: 'Find the longest substring with at most 3 distinct characters.',
    choices: ['Sliding window', 'Opposite-end two pointers', 'Binary search', 'Stack'],
    answer: 'Sliding window',
    signal: 'Longest contiguous range with a dynamic constraint',
    explanation: 'A sliding window also uses two boundaries, but the defining idea is maintaining a valid contiguous window as it expands and shrinks.',
  },
  {
    id: 'two-pointers-pattern-5',
    prompt: 'Find two values in an unsorted array that add to target in expected O(n) time without sorting.',
    choices: ['Hash map', 'Two pointers immediately', 'Stack', 'Queue'],
    answer: 'Hash map',
    signal: 'Unsorted + complement lookup',
    explanation: 'Without useful order, moving a left or right pointer does not safely eliminate possibilities. A hash map gives fast complement lookup.',
  },
]

export const predictionQuestions: ChoiceQuestion[] = [
  {
    id: 'two-pointers-predict-1',
    prompt: 'Sorted nums = [1, 3, 6, 9], target = 10. left=0, right=3 gives sum…',
    choices: ['4', '9', '10', '12'],
    answer: '10',
    explanation: 'nums[0] + nums[3] = 1 + 9 = 10, so the pair is found immediately.',
  },
  {
    id: 'two-pointers-predict-2',
    prompt: 'In sorted two-sum, current sum is smaller than target. Which pointer moves?',
    choices: ['left moves right', 'right moves left', 'both reset', 'neither'],
    answer: 'left moves right',
    explanation: 'To make the sum larger, discard the current smallest value by moving left to a larger value.',
  },
  {
    id: 'two-pointers-predict-3',
    prompt: 'Opposite-end pointers usually finish after at most about…',
    choices: ['n pointer moves', 'n² pointer moves', 'log n pointer moves', 'constant moves'],
    answer: 'n pointer moves',
    explanation: 'Each move brings one pointer inward, so the total movement is linear.',
  },
  {
    id: 'two-pointers-predict-4',
    prompt: 'The biggest advantage over a hash-map pair solution on sorted input is often…',
    choices: ['O(1) extra space', 'O(1) total time', 'No comparisons', 'No loop'],
    answer: 'O(1) extra space',
    explanation: 'Both can be linear time, but two pointers can exploit sorted order without storing a map.',
  },
]

export const complexityQuestions: ChoiceQuestion[] = [
  {
    id: 'two-pointers-complexity-1',
    prompt: 'Two pointers start at opposite ends and each only moves inward. Time is usually…',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(n)',
    explanation: 'No pointer moves backwards over work already completed; together they cross the input once.',
  },
  {
    id: 'two-pointers-complexity-2',
    prompt: 'If the two-pointer algorithm stores only left, right and a few variables, extra space is…',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(1)',
    explanation: 'The number of stored variables does not grow with input size.',
  },
  {
    id: 'two-pointers-complexity-3',
    prompt: 'Sort an unsorted array first, then use two pointers. Total time is usually dominated by…',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    answer: 'O(n log n)',
    explanation: 'The pointer pass is O(n), but sorting typically costs O(n log n).',
  },
  {
    id: 'two-pointers-complexity-4',
    prompt: 'Nested loops checking every pair versus two pointers on sorted input changes pair-search time from…',
    choices: ['O(n²) to O(n)', 'O(n) to O(1)', 'O(log n) to O(n)', 'O(n) to O(n²)'],
    answer: 'O(n²) to O(n)',
    explanation: 'Sorted order lets each comparison safely eliminate an entire side of impossible pairs.',
  },
  {
    id: 'two-pointers-complexity-5',
    prompt: 'Why does the sorted two-sum pointer movement work?',
    choices: ['Order makes each move eliminate impossible pairs', 'Hashing happens automatically', 'The array is copied', 'Every pair is still checked'],
    answer: 'Order makes each move eliminate impossible pairs',
    explanation: 'If the sum is too small, pairing the current left value with any smaller right value would not help; similarly for sums that are too large.',
  },
]

export const mixedQuestions: ChoiceQuestion[] = [
  {
    id: 'two-pointers-mixed-1',
    prompt: 'Sorted array. Determine whether any pair sums to 25.',
    choices: ['Two pointers', 'Hash map', 'Sliding window', 'Stack', 'Queue', 'Prefix sum'],
    answer: 'Two pointers',
    signal: 'Sorted + pair target',
    explanation: 'Opposite ends let the current sum tell you which side to move.',
  },
  {
    id: 'two-pointers-mixed-2',
    prompt: 'Unsorted array. Return indices of two numbers adding to target in O(n) expected time.',
    choices: ['Hash map', 'Two pointers without sorting', 'Stack', 'Queue', 'Prefix sum', 'Binary search'],
    answer: 'Hash map',
    signal: 'Unsorted + complement + preserve indices',
    explanation: 'A map remembers values and indices while preserving original positions.',
  },
  {
    id: 'two-pointers-mixed-3',
    prompt: 'Check whether "A man a plan a canal Panama" is a palindrome while skipping spaces and case.',
    choices: ['Two pointers', 'Prefix sum', 'Queue', 'Binary search', 'Hash map', 'Sorting'],
    answer: 'Two pointers',
    signal: 'Mirrored comparison + skip irrelevant characters',
    explanation: 'Move each side inward, skipping characters that should not participate, then compare the next valid pair.',
  },
  {
    id: 'two-pointers-mixed-4',
    prompt: 'Find the maximum sum of any contiguous subarray of length 4.',
    choices: ['Sliding window', 'Two pointers opposite ends', 'Hash map', 'Stack', 'Queue', 'Binary search'],
    answer: 'Sliding window',
    signal: 'Fixed-size contiguous range',
    explanation: 'Maintain the sum of exactly four adjacent values as the window slides.',
  },
  {
    id: 'two-pointers-mixed-5',
    prompt: 'Remove duplicates from a sorted array and return the unique values in order.',
    choices: ['Fast/slow two pointers', 'Hash set only', 'Stack', 'Queue', 'Prefix sum', 'Binary search'],
    answer: 'Fast/slow two pointers',
    signal: 'Sorted + compact output in order',
    explanation: 'A slow pointer tracks the compacted unique prefix while a fast pointer scans new candidates.',
  },
  {
    id: 'two-pointers-mixed-6',
    prompt: 'Find whether target 82 exists in a sorted array.',
    choices: ['Binary search', 'Two pointers', 'Hash set', 'Sliding window', 'Stack', 'Queue'],
    answer: 'Binary search',
    signal: 'Sorted + one exact target',
    explanation: 'For one target value, binary search discards half the remaining search space each step.',
  },
  {
    id: 'two-pointers-mixed-7',
    prompt: 'Count the frequency of every integer in an unsorted list.',
    choices: ['Hash map', 'Two pointers', 'Binary search', 'Stack', 'Queue', 'Prefix sum'],
    answer: 'Hash map',
    signal: 'Frequency by value',
    explanation: 'Each distinct integer needs an associated count.',
  },
]

export const challenges: CodeChallengeData[] = [
  {
    id: 'two-pointers-guided-pair-sum',
    eyebrow: 'Guided challenge',
    title: 'Pair sum in sorted data',
    difficulty: 'Guided',
    description: 'Given a sorted array of numbers, return true if any two different elements add to target.',
    examples: ['hasPairWithSum([1, 2, 4, 7, 11], 9) → true', 'hasPairWithSum([1, 2, 4], 10) → false'],
    constraints: ['0 ≤ nums.length ≤ 100,000', 'nums is sorted ascending'],
    starter: `function hasPairWithSum(nums: number[], target: number): boolean {\n  let left = 0;\n  let right = nums.length - 1;\n\n  // Move the correct pointer based on the current sum.\n  return false;\n}`,
    functionName: 'hasPairWithSum',
    tests: [
      { label: 'pair exists', args: [[1, 2, 4, 7, 11], 9], expected: true },
      { label: 'no pair', args: [[1, 2, 4], 10], expected: false },
      { label: 'negative values', args: [[-5, -1, 2, 8], 3], expected: true },
      { label: 'too short', args: [[5], 10], expected: false },
    ],
    hints: [
      'Start with the smallest and largest values.',
      'If the sum is too small, only moving left can increase it in a useful way.',
      'If the sum is too large, move right leftward to reduce it.',
    ],
    solution: `function hasPairWithSum(nums: number[], target: number): boolean {\n  let left = 0;\n  let right = nums.length - 1;\n\n  while (left < right) {\n    const sum = nums[left] + nums[right];\n    if (sum === target) return true;\n    if (sum < target) left++;\n    else right--;\n  }\n\n  return false;\n}`,
    solutionExplanation: 'Sorted order makes each comparison informative: the sum tells you which side can be discarded safely.',
    time: 'O(n)',
    space: 'O(1)',
    remember: 'Two pointers works when pointer movement can eliminate possibilities, not merely because there are two indices.',
  },
  {
    id: 'two-pointers-independent-palindrome',
    eyebrow: 'Independent 1',
    title: 'Palindrome check',
    difficulty: 'Independent',
    description: 'Return true if a lowercase string reads the same forwards and backwards. Do not create a reversed copy.',
    examples: ['isPalindrome("racecar") → true', 'isPalindrome("pattern") → false'],
    constraints: ['0 ≤ s.length ≤ 100,000', 'Input contains lowercase a–z only'],
    starter: `function isPalindrome(s: string): boolean {\n  // Your solution\n  return false;\n}`,
    functionName: 'isPalindrome',
    tests: [
      { label: 'palindrome', args: ['racecar'], expected: true },
      { label: 'not palindrome', args: ['pattern'], expected: false },
      { label: 'even length', args: ['abba'], expected: true },
      { label: 'empty', args: [''], expected: true },
    ],
    hints: [
      'Compare the first and last characters, then move inward.',
      'Stop as soon as a pair does not match.',
      'The pointers only need to continue while left < right.',
    ],
    solution: `function isPalindrome(s: string): boolean {\n  let left = 0;\n  let right = s.length - 1;\n\n  while (left < right) {\n    if (s[left] !== s[right]) return false;\n    left++;\n    right--;\n  }\n\n  return true;\n}`,
    solutionExplanation: 'Each comparison checks one mirrored pair, and both pointers move inward exactly once per pair.',
    time: 'O(n)',
    space: 'O(1)',
    remember: 'Mirrored comparison is a direct opposite-end two-pointer signal.',
  },
  {
    id: 'two-pointers-independent-unique-sorted',
    eyebrow: 'Independent 2',
    title: 'Unique values from sorted input',
    difficulty: 'Independent',
    description: 'Given a sorted array, return a new array containing one copy of each distinct value in the same order.',
    examples: ['uniqueSorted([1, 1, 2, 2, 2, 5]) → [1, 2, 5]'],
    constraints: ['0 ≤ nums.length ≤ 100,000', 'nums is sorted ascending'],
    starter: `function uniqueSorted(nums: number[]): number[] {\n  // Think slow/fast: what did the last accepted value look like?\n  return [];\n}`,
    functionName: 'uniqueSorted',
    tests: [
      { label: 'duplicates', args: [[1, 1, 2, 2, 2, 5]], expected: [1, 2, 5] },
      { label: 'already unique', args: [[1, 2, 3]], expected: [1, 2, 3] },
      { label: 'all same', args: [[4, 4, 4]], expected: [4] },
      { label: 'empty', args: [[]], expected: [] },
    ],
    hints: [
      'Because the input is sorted, duplicates sit next to each other.',
      'A fast pointer scans candidates; the accepted output behaves like the slow side.',
      'Only append when the current value differs from the last accepted value.',
    ],
    solution: `function uniqueSorted(nums: number[]): number[] {\n  if (nums.length === 0) return [];\n\n  const result = [nums[0]];\n  for (let fast = 1; fast < nums.length; fast++) {\n    if (nums[fast] !== result[result.length - 1]) {\n      result.push(nums[fast]);\n    }\n  }\n\n  return result;\n}`,
    solutionExplanation: 'Sorted order groups equal values, so the fast scan only needs to compare with the last value accepted into the compact output.',
    time: 'O(n)',
    space: 'O(n)',
    remember: 'Fast/slow pointer thinking is about separating the scan position from the accepted or write position.',
  },
]
