import type { ChoiceQuestion, CodeChallengeData } from '../../types'

export const patternQuestions: ChoiceQuestion[] = [
  {
    id: 'pattern-1',
    prompt: 'You need to visit every daily temperature once and calculate the average.',
    choices: ['Array traversal', 'Binary search', 'Stack', 'Hash map'],
    answer: 'Array traversal',
    signal: 'Visit every value once',
    explanation: 'The data is already stored sequentially and every element matters. A single left-to-right pass is the natural fit.',
    tempting: 'Binary search only helps when you can discard large parts of sorted search space. Here, you must inspect every temperature.',
  },
  {
    id: 'pattern-2',
    prompt: 'Given a sorted array, find whether the number 73 exists.',
    choices: ['Array traversal', 'Binary search', 'Queue', 'Recursion only'],
    answer: 'Binary search',
    signal: 'Sorted input + find one target',
    explanation: 'Sorted order lets you eliminate half of the remaining array after each comparison.',
    tempting: 'A linear array traversal works, but it ignores the strongest clue: sorted input.',
  },
  {
    id: 'pattern-3',
    prompt: 'Find the longest contiguous run of days whose total spend stays under £100.',
    choices: ['Sliding window', 'Stack', 'Hash set', 'Sorting'],
    answer: 'Sliding window',
    signal: 'Longest + contiguous range + changing boundary',
    explanation: 'A sliding window is built for maintaining a changing contiguous section while moving through an array.',
    tempting: 'Sorting would destroy the original adjacency, which is essential because the range must be contiguous.',
  },
  {
    id: 'pattern-4',
    prompt: 'Check whether any username appears twice in a large list.',
    choices: ['Hash set', 'Array insertion', 'Binary search', 'Queue'],
    answer: 'Hash set',
    signal: 'Fast membership / seen-before lookup',
    explanation: 'A set can remember seen usernames and usually check membership in constant average time.',
    tempting: 'Comparing every pair in the array works but becomes O(n²).',
  },
  {
    id: 'pattern-5',
    prompt: 'You receive scores in order and simply need the highest score.',
    choices: ['Array traversal', 'Sorting', 'Stack', 'Linked list'],
    answer: 'Array traversal',
    signal: 'Need one aggregate answer from all items',
    explanation: 'Track the best score while scanning once. You do not need to rearrange or copy the data.',
    tempting: 'Sorting can place the maximum at an end, but O(n log n) work is unnecessary when one O(n) pass is enough.',
  },
]

export const predictionQuestions: ChoiceQuestion[] = [
  {
    id: 'predict-1',
    prompt: 'const xs = [4, 8, 12]; xs[1] = 9; console.log(xs[1]);',
    choices: ['8', '9', '12', 'undefined'],
    answer: '9',
    explanation: 'Arrays give direct access by index. Index 1 points to the second slot, and the assignment replaces 8 with 9.',
  },
  {
    id: 'predict-2',
    prompt: 'const xs = [10, 20, 30]; xs.push(40); What is xs.length?',
    choices: ['3', '4', '40', 'undefined'],
    answer: '4',
    explanation: 'push appends one element to the end, so the length increases from 3 to 4.',
  },
  {
    id: 'predict-3',
    prompt: 'Reading xs[i] from a normal array by a known valid index is usually…',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(1)',
    explanation: 'The index gives a direct route to the slot; you do not need to scan earlier elements.',
  },
  {
    id: 'predict-4',
    prompt: 'Inserting at index 0 of a JavaScript array with unshift usually requires…',
    choices: ['No other work', 'Shifting many existing elements', 'Binary search', 'Reversing the array'],
    answer: 'Shifting many existing elements',
    explanation: 'The existing elements need new indices so the new value can occupy index 0. That makes front insertion O(n).',
  },
]

export const complexityQuestions: ChoiceQuestion[] = [
  {
    id: 'complexity-1',
    prompt: 'Read nums[500] when the index is already known.',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(1)',
    explanation: 'Direct indexed access does not depend on the array length.',
  },
  {
    id: 'complexity-2',
    prompt: 'Scan an array once to count negative values.',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(n)',
    explanation: 'Every item may need to be inspected once.',
  },
  {
    id: 'complexity-3',
    prompt: 'Compare every pair of elements using two nested loops.',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(n²)',
    explanation: 'Roughly n choices are paired with roughly n choices, producing quadratic growth.',
  },
  {
    id: 'complexity-4',
    prompt: 'Which usually scales better for finding the maximum?',
    choices: ['Sort O(n log n)', 'One pass O(n)', 'They scale the same', 'Nested loops O(n²)'],
    answer: 'One pass O(n)',
    explanation: 'The maximum can be maintained as you scan, so sorting performs extra work you do not need.',
  },
  {
    id: 'complexity-5',
    prompt: 'If n grows from 1,000 to 1,000,000, which growth rate becomes dangerous fastest?',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(n²)',
    explanation: 'Quadratic work grows with the square of the input size. At one million items, pairwise work can become enormous.',
  },
]

export const mixedQuestions: ChoiceQuestion[] = [
  {
    id: 'mixed-1',
    prompt: 'A sorted list of IDs. Determine whether ID 840291 exists.',
    choices: ['Array traversal', 'Hash map', 'Two pointers', 'Sliding window', 'Prefix sum', 'Sorting', 'Binary search', 'Stack', 'Queue', 'Brute force / no special pattern'],
    answer: 'Binary search',
    signal: 'Sorted array + target lookup',
    explanation: 'Sorted order lets you repeatedly discard half the remaining candidates.',
  },
  {
    id: 'mixed-2',
    prompt: 'Find two numbers in a sorted array whose sum equals a target.',
    choices: ['Array traversal', 'Hash map', 'Two pointers', 'Sliding window', 'Prefix sum', 'Sorting', 'Binary search', 'Stack', 'Queue', 'Brute force / no special pattern'],
    answer: 'Two pointers',
    signal: 'Sorted array + pair of values',
    explanation: 'One pointer can start low and one high. The sum tells you which side can safely move inward.',
  },
  {
    id: 'mixed-3',
    prompt: 'Answer many queries asking for the sum between index L and R in the same numeric array.',
    choices: ['Array traversal', 'Hash map', 'Two pointers', 'Sliding window', 'Prefix sum', 'Sorting', 'Binary search', 'Stack', 'Queue', 'Brute force / no special pattern'],
    answer: 'Prefix sum',
    signal: 'Many repeated range-sum queries',
    explanation: 'Precompute cumulative totals once, then each range sum can be recovered from two prefix values.',
  },
  {
    id: 'mixed-4',
    prompt: 'Return the first repeated email address while scanning a list.',
    choices: ['Array traversal', 'Hash set', 'Two pointers', 'Sliding window', 'Prefix sum', 'Sorting', 'Binary search', 'Stack', 'Queue', 'Brute force / no special pattern'],
    answer: 'Hash set',
    signal: 'Seen before? + fast membership',
    explanation: 'A set stores previously seen values and supports fast average membership checks.',
  },
  {
    id: 'mixed-5',
    prompt: 'Find the maximum sum among all contiguous subarrays of exactly length 5.',
    choices: ['Array traversal', 'Hash map', 'Two pointers', 'Sliding window', 'Prefix sum', 'Sorting', 'Binary search', 'Stack', 'Queue', 'Brute force / no special pattern'],
    answer: 'Sliding window',
    signal: 'Contiguous subarray + fixed length',
    explanation: 'Keep the sum of five items, subtract the element leaving the window, and add the new one entering.',
  },
  {
    id: 'mixed-6',
    prompt: 'Validate whether brackets in "([]{})" are correctly nested.',
    choices: ['Array traversal', 'Hash map', 'Two pointers', 'Sliding window', 'Prefix sum', 'Sorting', 'Binary search', 'Stack', 'Queue', 'Brute force / no special pattern'],
    answer: 'Stack',
    signal: 'Most recent unmatched item must be handled first',
    explanation: 'Bracket matching is last-in, first-out: each closing bracket must match the most recent opening bracket.',
  },
  {
    id: 'mixed-7',
    prompt: 'Given 30 numbers, print each one doubled. There is no search, pairing, range query, or special constraint.',
    choices: ['Array traversal', 'Hash map', 'Two pointers', 'Sliding window', 'Prefix sum', 'Sorting', 'Binary search', 'Stack', 'Queue', 'Brute force / no special pattern'],
    answer: 'Array traversal',
    signal: 'Do the same simple operation to every item',
    explanation: 'A direct traversal is enough. Pattern recognition also means noticing when no more specialised technique is needed.',
  },
]

export const challenges: CodeChallengeData[] = [
  {
    id: 'guided-sum-positive',
    eyebrow: 'Guided challenge',
    title: 'Sum the positive values',
    difficulty: 'Guided',
    description: 'Given an array of numbers, return the sum of only the values greater than zero. Empty arrays should return 0.',
    examples: ['sumPositive([-2, 5, 3, -1]) → 8', 'sumPositive([]) → 0'],
    constraints: ['0 ≤ nums.length ≤ 100,000', 'Each number is a finite integer'],
    starter: `function sumPositive(nums: number[]): number {\n  // Think: what single piece of state do you need?\n  return 0;\n}`,
    functionName: 'sumPositive',
    tests: [
      { label: 'mixed signs', args: [[-2, 5, 3, -1]], expected: 8 },
      { label: 'empty array', args: [[]], expected: 0 },
      { label: 'all negative', args: [[-4, -1, -9]], expected: 0 },
      { label: 'all positive', args: [[1, 2, 3, 4]], expected: 10 },
    ],
    hints: [
      'You need to inspect each value, so start with a single traversal.',
      'Keep a running total. Only update it when the current number is positive.',
      'Pseudocode: total = 0 → for each num → if num > 0, total += num → return total.',
    ],
    solution: `function sumPositive(nums: number[]): number {\n  let total = 0;\n\n  for (const num of nums) {\n    if (num > 0) total += num;\n  }\n\n  return total;\n}`,
    solutionExplanation: 'The algorithm stores one running total and visits each element exactly once. No reordering or extra data structure is needed.',
    time: 'O(n)',
    space: 'O(1)',
    remember: 'If the answer is an aggregate of all elements, first ask whether one pass with a small amount of state is enough.',
  },
  {
    id: 'independent-max',
    eyebrow: 'Independent 1',
    title: 'Find the maximum',
    difficulty: 'Independent',
    description: 'Return the largest number in a non-empty array. Do not sort the array.',
    examples: ['findMax([4, 1, 9, 2]) → 9', 'findMax([-8, -2, -11]) → -2'],
    constraints: ['1 ≤ nums.length ≤ 100,000', 'Do not use sort()'],
    starter: `function findMax(nums: number[]): number {\n  // Your solution\n  return 0;\n}`,
    functionName: 'findMax',
    tests: [
      { label: 'basic', args: [[4, 1, 9, 2]], expected: 9 },
      { label: 'negative values', args: [[-8, -2, -11]], expected: -2 },
      { label: 'single item', args: [[7]], expected: 7 },
      { label: 'duplicate max', args: [[5, 9, 9, 1]], expected: 9 },
    ],
    hints: [
      'You only need to remember the best value seen so far.',
      'Initialise from nums[0], not 0 — the entire array could be negative.',
      'Scan from index 1. If nums[i] is greater than currentMax, replace currentMax.',
    ],
    solution: `function findMax(nums: number[]): number {\n  let currentMax = nums[0];\n\n  for (let i = 1; i < nums.length; i++) {\n    if (nums[i] > currentMax) currentMax = nums[i];\n  }\n\n  return currentMax;\n}`,
    solutionExplanation: 'The maximum is a running summary. Every new value either leaves the summary unchanged or becomes the new maximum.',
    time: 'O(n)',
    space: 'O(1)',
    remember: 'For min/max over an unsorted array, a one-pass running answer is usually better than sorting.',
  },
  {
    id: 'independent-remove-at',
    eyebrow: 'Independent 2',
    title: 'Remove one index',
    difficulty: 'Independent',
    description: 'Return a new array containing every element except the item at the given valid index. Do not mutate the input.',
    examples: ['removeAt([10, 20, 30, 40], 1) → [10, 30, 40]'],
    constraints: ['1 ≤ nums.length ≤ 100,000', '0 ≤ index < nums.length'],
    starter: `function removeAt(nums: number[], index: number): number[] {\n  // Your solution\n  return [];\n}`,
    functionName: 'removeAt',
    tests: [
      { label: 'middle', args: [[10, 20, 30, 40], 1], expected: [10, 30, 40] },
      { label: 'first', args: [[1, 2, 3], 0], expected: [2, 3] },
      { label: 'last', args: [[1, 2, 3], 2], expected: [1, 2] },
      { label: 'single item', args: [[5], 0], expected: [] },
    ],
    hints: [
      'You are building a new array, so think traversal plus a condition.',
      'Push each value except when its index equals the index to remove.',
      'Pseudocode: result = [] → loop i → if i !== index push nums[i] → return result.',
    ],
    solution: `function removeAt(nums: number[], index: number): number[] {\n  const result: number[] = [];\n\n  for (let i = 0; i < nums.length; i++) {\n    if (i !== index) result.push(nums[i]);\n  }\n\n  return result;\n}`,
    solutionExplanation: 'Because the result must be a new array, you need O(n) output space in the worst case. The traversal copies every item except one.',
    time: 'O(n)',
    space: 'O(n)',
    remember: 'When producing a transformed array, be explicit about whether mutation is allowed. That decision changes the space story.',
  },
  {
    id: 'independent-second-largest',
    eyebrow: 'Independent 3',
    title: 'Second-largest distinct value',
    difficulty: 'Independent',
    description: 'Return the second-largest distinct number. The input always contains at least two distinct values. Try to beat sorting.',
    examples: ['secondLargest([4, 9, 2, 9, 7]) → 7'],
    constraints: ['2 ≤ nums.length ≤ 100,000', 'At least two distinct values'],
    starter: `function secondLargest(nums: number[]): number {\n  // Can you do this in one pass?\n  return 0;\n}`,
    functionName: 'secondLargest',
    tests: [
      { label: 'duplicates', args: [[4, 9, 2, 9, 7]], expected: 7 },
      { label: 'negative', args: [[-10, -3, -7, -3]], expected: -7 },
      { label: 'two values', args: [[5, 1]], expected: 1 },
      { label: 'descending', args: [[8, 7, 6, 5]], expected: 7 },
    ],
    hints: [
      'Sorting works in O(n log n), but the question only asks you to remember the two best distinct values.',
      'Track largest and secondLargest. Be careful not to treat a duplicate of largest as the second-largest distinct value.',
      'For each num: if num > largest, shift largest down; otherwise, if num < largest and num > second, update second.',
    ],
    solution: `function secondLargest(nums: number[]): number {\n  let largest = -Infinity;\n  let second = -Infinity;\n\n  for (const num of nums) {\n    if (num > largest) {\n      second = largest;\n      largest = num;\n    } else if (num < largest && num > second) {\n      second = num;\n    }\n  }\n\n  return second;\n}`,
    solutionExplanation: 'The brute-force instinct is often to sort, but that solves a larger problem than necessary. Maintaining the top two distinct values gives the answer in a single pass.',
    time: 'O(n)',
    space: 'O(1)',
    remember: 'Before sorting, ask: do I really need full order, or only a small amount of order information?',
  },
]
