import type { SystemDesignModuleConfig } from './SystemDesignModule'

export const systemDesignModules: Record<string, SystemDesignModuleConfig> = {
  'http-https': {
    id: 'http-https', order: 1, title: 'HTTP / HTTPS', subtitle: 'Requests, responses and secure web communication', duration: '35–45 min',
    heroTitle: 'HTTP is the conversation. HTTPS makes that conversation private and trustworthy.',
    heroDescription: 'Learn the request/response model underneath websites and APIs, then separate HTTP semantics from TLS security.',
    introLead: 'HTTP is an application-layer protocol for exchanging messages between a client and a server.',
    introBody: 'A client sends a request containing a method, path, headers and sometimes a body. A server returns a response containing a status code, headers and usually a body. HTTPS is HTTP carried through a TLS-secured connection, adding encryption, integrity and server authentication.',
    keyIdeas: [
      { label: 'REQUEST', title: 'Client asks', detail: 'Methods such as GET or POST describe the intent. Paths, headers and an optional body describe the request.' },
      { label: 'RESPONSE', title: 'Server answers', detail: 'Status codes such as 200, 404 and 500 summarise the outcome; headers and a body carry the result.' },
      { label: 'STATELESS', title: 'Each request stands alone', detail: 'HTTP does not automatically remember prior requests. Cookies, sessions and tokens add continuity above HTTP.' },
      { label: 'HTTPS', title: 'HTTP protected by TLS', detail: 'TLS encrypts traffic, detects tampering and helps the browser verify the server.' },
      { label: 'PORTS', title: '80 and 443 are common clues', detail: 'HTTP commonly uses port 80 and HTTPS commonly uses 443, although ports are configurable.' },
      { label: 'VERSIONS', title: 'Same semantics, newer transports', detail: 'HTTP/1.1, HTTP/2 and HTTP/3 differ in how messages travel, while methods, headers and status codes remain recognisably HTTP.' },
    ],
    rule: 'When you see endpoint, method, header, body or status code, locate the HTTP layer first. When you see certificate, encryption or secure connection, think TLS/HTTPS.',
    flowTitle: 'A simplified HTTPS request',
    flow: [
      { title: 'Destination is known', detail: 'Assume DNS has already resolved pact.me to an IP address.' },
      { title: 'Transport opens', detail: 'The browser establishes TCP for HTTP/1.1 or HTTP/2, or QUIC over UDP for HTTP/3.' },
      { title: 'TLS secures the connection', detail: 'The browser and server agree keys and the browser validates the server certificate.' },
      { title: 'Browser sends HTTP', detail: 'For example: GET / with headers such as Host, Accept and Cookie.' },
      { title: 'Server handles the request', detail: 'Web infrastructure and application code decide what to return.' },
      { title: 'HTTP response returns', detail: 'The browser receives a status code, headers and body, then renders or processes them.' },
    ],
    flowTakeaway: 'HTTP defines the messages. TCP or QUIC moves them. TLS protects them. Keeping those jobs separate is the key mental model.',
    clues: [['GET / POST / PATCH / DELETE', 'HTTP methods'], ['200 / 404 / 500', 'HTTP status codes'], ['headers / JSON / body', 'HTTP message structure'], ['certificate / encryption', 'HTTPS and TLS'], ['port 443', 'usually HTTPS traffic'], ['stateless API', 'HTTP itself does not remember earlier requests']],
    recognitionQuestions: [
      { id: 'http-r1', prompt: 'A mobile app sends POST /payments with JSON and receives 201 Created. Which layer is being described most directly?', choices: ['DNS', 'HTTP', 'TCP congestion control', 'IP routing'], answer: 'HTTP', explanation: 'Methods, paths, message bodies and status codes are HTTP concepts.' },
      { id: 'http-r2', prompt: 'What is the best description of HTTPS?', choices: ['A completely different replacement for HTTP', 'HTTP protected by TLS', 'HTTP that only supports GET', 'A DNS encryption protocol'], answer: 'HTTP protected by TLS', explanation: 'HTTPS keeps HTTP semantics while TLS provides encryption, integrity and authentication.' },
      { id: 'http-r3', prompt: 'A browser receives 404 Not Found. What does that prove?', choices: ['DNS failed', 'An HTTP response was received', 'TLS definitely failed', 'The TCP connection never opened'], answer: 'An HTTP response was received', explanation: '404 is an HTTP response, so the request made it far enough for the HTTP layer to answer.' },
    ],
    scenarioQuestions: [
      { id: 'http-s1', prompt: 'PACT creates a new payment-link resource. Which HTTP method is the most natural starting choice?', choices: ['GET', 'POST', 'HEAD', 'TRACE'], answer: 'POST', explanation: 'POST commonly creates a subordinate resource or triggers a state-changing action with a request body.' },
      { id: 'http-s2', prompt: 'The new PACT Link was successfully created. Which response is the strongest conventional fit?', choices: ['201 Created', '304 Not Modified', '404 Not Found', '503 Service Unavailable'], answer: '201 Created', explanation: '201 communicates successful resource creation.' },
      { id: 'http-s3', prompt: 'The request reached the application but the server crashed processing it. Which status-code family fits best?', choices: ['1xx', '2xx', '4xx', '5xx'], answer: '5xx', explanation: '5xx responses indicate server-side failures.' },
    ],
    explainPrompt: 'Explain HTTP vs HTTPS to a first-year CS student. Separate HTTP from TLS instead of saying “HTTPS is just a secure website”.',
    explainChecklist: ['HTTP defines request/response messages.', 'Requests have methods, paths, headers and sometimes bodies.', 'Responses have status codes, headers and often bodies.', 'TLS encrypts and protects the connection.', 'HTTPS is HTTP carried through TLS.'],
    modelAnswer: 'HTTP defines the messages exchanged between a client and server: things such as GET requests, headers, status codes and response bodies. HTTPS keeps those same HTTP semantics but sends them through a TLS-secured connection. TLS encrypts the traffic, detects tampering and lets the browser verify the server certificate. So HTTPS changes the security of the communication, not the basic meaning of HTTP requests and responses.',
    pactTitle: 'Where HTTP/HTTPS fits after you type pact.me',
    pactBody: 'HTTP is not the first thing that happens. The browser first needs a destination and transport path. Once those exist, HTTPS can secure the connection and the browser can ask pact.me for the page.',
    pactSteps: ['DNS resolves pact.me → an IP address', 'Transport opens → TCP or QUIC', 'TLS establishes a secure channel', 'Browser sends an HTTP GET request', 'PACT returns an HTTP response', 'Browser parses the response and requests additional resources'],
    revision: {
      headline: 'Messages first, security second.',
      thinkWhen: ['You see methods, endpoints, headers or status codes.', 'You need to describe browser ↔ server communication.', 'You need to separate application semantics from security/transport.'],
      vocabulary: ['request', 'response', 'method', 'status code', 'header', 'body', 'stateless', 'TLS', '443'],
      mistakes: ['Saying HTTPS is a totally different application protocol.', 'Confusing a 404 with a DNS failure.', 'Assuming HTTP itself provides encryption.', 'Treating cookies as proof HTTP is stateful.'],
      interviewQuestions: ['What is HTTP?', 'HTTP vs HTTPS?', 'What do 2xx, 4xx and 5xx mean?', 'Why is HTTP called stateless?'],
      sentence: 'HTTP defines the conversation; HTTPS is that conversation protected by TLS.',
    },
  },

  'tcp-vs-udp': {
    id: 'tcp-vs-udp', order: 2, title: 'TCP vs UDP', subtitle: 'Reliability, ordering and latency at the transport layer', duration: '35–45 min',
    heroTitle: 'TCP asks: “Did every byte arrive in order?” UDP asks: “Can I send this datagram now?”',
    heroDescription: 'Learn to choose between reliable ordered delivery and lightweight datagrams, then connect that choice to web traffic, DNS, games, voice calls and HTTP/3.',
    introLead: 'TCP and UDP are transport-layer protocols that carry application data between endpoints identified by IP addresses and ports.',
    introBody: 'TCP creates a connection and gives applications a reliable ordered byte stream. It detects missing data, retransmits losses and preserves order. UDP sends independent datagrams with much less built-in machinery: no connection handshake and no guarantee of delivery or ordering.',
    keyIdeas: [
      { label: 'TCP', title: 'Reliable ordered stream', detail: 'TCP sequences bytes, acknowledges delivery, retransmits losses and presents data in order.' },
      { label: 'HANDSHAKE', title: 'Connection-oriented', detail: 'TCP normally begins with a three-way handshake before application data is exchanged.' },
      { label: 'UDP', title: 'Independent datagrams', detail: 'UDP sends discrete messages without creating a reliable stream or waiting for protocol-level acknowledgements.' },
      { label: 'TRADE-OFF', title: 'Reliability costs coordination', detail: 'TCP maintains more state. UDP is lighter, but applications needing reliability must add it themselves or use a protocol that does.' },
      { label: 'PORTS', title: 'Both use ports', detail: 'TCP and UDP both use port numbers to help deliver traffic to the correct application process.' },
      { label: 'QUIC', title: 'HTTP/3 complicates the simple rule', detail: 'HTTP/1.1 and HTTP/2 commonly use TCP. HTTP/3 uses QUIC over UDP, with QUIC adding reliable streams itself.' },
    ],
    rule: 'Choose TCP when reliable ordered delivery is the default requirement. Consider UDP when timeliness or independent messages matter more — while remembering higher protocols can add reliability on top of UDP.',
    flowTitle: 'What the transport layer decides',
    flow: [
      { title: 'Application has data', detail: 'A browser, game, voice app or DNS resolver needs to send something.' },
      { title: 'Choose delivery behaviour', detail: 'Do you need every byte reliably and in order, or are independent datagrams a better fit?' },
      { title: 'TCP path', detail: 'Connect → sequence → acknowledge → retransmit losses → deliver ordered bytes.' },
      { title: 'UDP path', detail: 'Create datagram → send → no built-in promise it arrives or arrives in order.' },
      { title: 'Application receives data', detail: 'TCP exposes a byte stream; UDP exposes individual datagrams.' },
      { title: 'Higher-level protocol adds meaning', detail: 'HTTP, DNS, games and other application protocols decide what the bytes/datagrams mean.' },
    ],
    flowTakeaway: 'TCP and UDP do not define webpages or domain names. They define transport behaviour. Ask what delivery guarantees the application needs.',
    clues: [['reliable / ordered / retransmit', 'think TCP'], ['live voice / game position / freshness', 'often think UDP'], ['three-way handshake', 'TCP setup'], ['datagram', 'UDP vocabulary'], ['HTTP/2', 'commonly TCP'], ['HTTP/3 / QUIC', 'UDP underneath, QUIC adds reliability']],
    recognitionQuestions: [
      { id: 'tcp-r1', prompt: 'A protocol guarantees bytes reach the application in order and retransmits lost data. Which transport is it?', choices: ['TCP', 'UDP', 'DNS', 'HTTP'], answer: 'TCP', explanation: 'Reliable ordered byte-stream delivery is TCP’s core abstraction.' },
      { id: 'tcp-r2', prompt: 'A game sends frequent player-position updates; a new update can make an old lost update irrelevant. Which transport is a natural candidate?', choices: ['UDP', 'TCP only', 'DNS', 'TLS'], answer: 'UDP', explanation: 'For rapidly superseded real-time updates, freshness can matter more than recovering every old message.' },
      { id: 'tcp-r3', prompt: 'Which statement about HTTP/3 is correct?', choices: ['It runs directly on DNS', 'It uses QUIC over UDP', 'It removes reliability', 'It requires plain HTTP'], answer: 'It uses QUIC over UDP', explanation: 'QUIC runs over UDP but supplies reliable streams and congestion control for HTTP/3.' },
    ],
    scenarioQuestions: [
      { id: 'tcp-s1', prompt: 'You are transferring a database backup where every byte must arrive correctly and in order. Best default transport?', choices: ['TCP', 'Raw UDP with no added reliability', 'DNS', 'ICMP'], answer: 'TCP', explanation: 'A reliable ordered stream maps naturally to a loss-intolerant file transfer.' },
      { id: 'tcp-s2', prompt: 'You are sending live microphone frames. A frame arriving five seconds late is nearly useless. Which requirement pushes toward UDP-style delivery?', choices: ['Freshness and latency', 'Strict recovery of every stale frame', 'Domain-name resolution', 'HTTP caching'], answer: 'Freshness and latency', explanation: 'Real-time media often values timely new data over blocking on recovery of old data.' },
      { id: 'tcp-s3', prompt: 'PACT is served over HTTP/2. Which transport would you normally expect underneath?', choices: ['TCP', 'UDP only', 'DNS', 'ARP'], answer: 'TCP', explanation: 'HTTP/2 normally runs over TCP. HTTP/3 is the web version that moves to QUIC over UDP.' },
    ],
    explainPrompt: 'Explain TCP vs UDP as an engineering trade-off. Include one example where TCP fits and one where UDP fits.',
    explainChecklist: ['TCP is connection-oriented.', 'TCP gives a reliable ordered byte stream.', 'UDP sends independent datagrams without delivery/order guarantees.', 'TCP fits data where every byte matters.', 'UDP can fit real-time data where stale retransmissions are less useful.', 'HTTP/3 uses QUIC over UDP.'],
    modelAnswer: 'TCP gives an application a reliable ordered stream. It establishes a connection, tracks sequence numbers, acknowledges data and retransmits losses, which fits things such as file transfer or HTTP/2 where missing bytes would corrupt the result. UDP sends independent datagrams without those guarantees, so it has less built-in coordination and can fit real-time traffic such as voice or game updates where fresh data matters more than recovering every stale packet. HTTP/3 uses QUIC over UDP, with QUIC adding the reliability the web still needs.',
    pactTitle: 'Where TCP/UDP fits after you type pact.me',
    pactBody: 'Once DNS gives the browser an IP address, the browser needs a transport path to the server. The exact transport depends on which HTTP version is used.',
    pactSteps: ['DNS gives the browser an IP address', 'HTTP/1.1 or HTTP/2 → usually TCP to port 443', 'HTTP/3 → QUIC over UDP to port 443', 'TLS/security is established', 'HTTP requests and responses travel over the transport', 'Loss and ordering are handled by TCP or QUIC'],
    revision: {
      headline: 'Delivery guarantees are the pattern.',
      thinkWhen: ['You are comparing reliability with latency.', 'You see ordered, retransmit, datagram or real-time.', 'You need to explain what sits below HTTP or DNS.'],
      vocabulary: ['connection', 'stream', 'datagram', 'sequence', 'ACK', 'retransmission', 'port', 'QUIC'],
      mistakes: ['Saying UDP is always faster in every useful sense.', 'Saying UDP can never be reliable.', 'Saying all web traffic uses TCP.', 'Confusing ports with IP addresses.'],
      interviewQuestions: ['TCP vs UDP?', 'What does the TCP handshake do?', 'Why might a game use UDP?', 'How can HTTP/3 be reliable over UDP?'],
      sentence: 'TCP gives you a reliable ordered stream; UDP gives you datagrams and lets higher layers decide what guarantees to add.',
    },
  },

  dns: {
    id: 'dns', order: 3, title: 'DNS', subtitle: 'How domain names become network destinations', duration: '40–45 min',
    heroTitle: 'DNS is the internet’s naming system: pact.me is useful to humans; IP addresses are useful to networks.',
    heroDescription: 'Trace a lookup through caches, recursive resolvers and authoritative nameservers, then connect the answer to the transport and HTTP layers you already learned.',
    introLead: 'DNS translates names such as pact.me into records computers can use, most famously IP addresses.',
    introBody: 'Your browser does not usually begin by asking a root server itself. It checks nearby caches and then relies on a recursive resolver. If the answer is not cached, that resolver follows the DNS hierarchy until it reaches a server that can provide an authoritative answer, caches the result for its TTL, and returns it to you.',
    keyIdeas: [
      { label: 'RECORDS', title: 'Names map to useful data', detail: 'A records map names to IPv4 addresses; AAAA records map to IPv6. DNS supports many other record types too.' },
      { label: 'CACHE', title: 'Lookups reuse answers', detail: 'Browsers, operating systems and recursive resolvers cache answers so every visit does not need a full hierarchy walk.' },
      { label: 'RESOLVER', title: 'A recursive resolver does the chasing', detail: 'Your configured resolver obtains the final answer on the client’s behalf.' },
      { label: 'HIERARCHY', title: 'Root → TLD → authoritative', detail: 'If uncached, the resolver follows delegation from root servers to the .me TLD and then to pact.me’s authoritative nameserver.' },
      { label: 'TTL', title: 'Cached answers expire', detail: 'A record’s time-to-live tells caches how long they may reuse an answer before refreshing it.' },
      { label: 'BOUNDARY', title: 'DNS does not fetch the website', detail: 'DNS gives information such as an IP address. The browser still has to connect and then speak HTTPS/HTTP.' },
    ],
    rule: 'If a hostname cannot become a usable destination, think DNS. If the hostname resolves correctly but the connection still fails, move on to transport, ports, TLS and the application.',
    flowTitle: 'An uncached lookup for pact.me',
    flow: [
      { title: 'Browser / OS cache', detail: 'The device first checks whether it already knows a fresh answer.' },
      { title: 'Recursive resolver', detail: 'If not, the device asks its configured DNS resolver.' },
      { title: 'Root nameserver', detail: 'The resolver can ask where the .me top-level domain is handled.' },
      { title: '.me TLD nameserver', detail: 'The resolver asks which nameservers are authoritative for pact.me.' },
      { title: 'Authoritative nameserver', detail: 'The resolver asks for the actual pact.me record.' },
      { title: 'Answer + cache', detail: 'The resolver returns the record and caches it according to its TTL.' },
    ],
    flowTakeaway: 'The hierarchy is a delegation system. Root servers do not store every website’s IP address; they tell resolvers where to look next.',
    clues: [['domain / hostname / resolve', 'think DNS'], ['A record', 'IPv4 address'], ['AAAA record', 'IPv6 address'], ['CNAME', 'alias to another DNS name'], ['TTL / cache', 'how long an answer can be reused'], ['root / TLD / authoritative', 'DNS hierarchy']],
    recognitionQuestions: [
      { id: 'dns-r1', prompt: 'A browser knows api.pact.me but not the server IP address. Which system solves that naming problem?', choices: ['DNS', 'HTTP status codes', 'TCP retransmission', 'TLS encryption'], answer: 'DNS', explanation: 'DNS resolves names into records such as IP addresses.' },
      { id: 'dns-r2', prompt: 'What does an A record normally contain?', choices: ['An IPv4 address', 'An HTTP response body', 'A TCP port', 'A TLS private key'], answer: 'An IPv4 address', explanation: 'A maps a name to IPv4; AAAA is the IPv6 equivalent.' },
      { id: 'dns-r3', prompt: 'Who should ultimately provide the authoritative answer for a pact.me record?', choices: ['A nameserver authoritative for pact.me', 'The browser rendering engine', 'Any root server directly', 'The HTTP application server because DNS is HTTP'], answer: 'A nameserver authoritative for pact.me', explanation: 'Root and TLD servers mainly delegate. The authoritative nameserver provides the domain’s record.' },
    ],
    scenarioQuestions: [
      { id: 'dns-s1', prompt: 'pact.me returns “server IP address could not be found” before any page loads. What should you inspect first?', choices: ['DNS configuration / resolution', 'Database indexes', 'React rendering', 'HTTP 500 handling'], answer: 'DNS configuration / resolution', explanation: 'The browser is failing before it can identify a destination server.' },
      { id: 'dns-s2', prompt: 'You want www.pact.me to be an alias of another hostname managed by your hosting platform. Which record is commonly used?', choices: ['CNAME', 'HTTP 301', 'TCP ACK', 'POST'], answer: 'CNAME', explanation: 'CNAME aliases one DNS name to another DNS name.' },
      { id: 'dns-s3', prompt: 'pact.me resolves to the correct IP, but connections to port 443 time out. Is DNS still the strongest first suspect?', choices: ['No — resolution succeeded; investigate transport/network/service next', 'Yes — every port failure is DNS', 'Yes — DNS owns port 443', 'No — it must be an HTTP 404'], answer: 'No — resolution succeeded; investigate transport/network/service next', explanation: 'Once the correct IP is resolved, a connection timeout points further along the request path.' },
    ],
    explainPrompt: 'Explain an uncached DNS lookup for pact.me. Name the recursive resolver and the root → TLD → authoritative hierarchy.',
    explainChecklist: ['The device checks local/browser caches.', 'The client asks a recursive resolver.', 'The resolver may consult a root nameserver.', 'Root delegates toward the .me TLD.', 'The TLD delegates toward pact.me’s authoritative nameserver.', 'The authoritative answer is returned and cached according to TTL.', 'Only then does the browser connect to the destination.'],
    modelAnswer: 'The browser or operating system first checks whether it already has a fresh cached DNS answer for pact.me. If not, it asks its configured recursive resolver. If that resolver also lacks a cached answer, it can ask a root nameserver where the .me TLD is handled, then ask a .me nameserver which nameservers are authoritative for pact.me, and finally ask an authoritative nameserver for the actual record such as an A or AAAA address. The resolver returns that answer to the client and caches it according to the TTL. The browser can then use the IP address to begin the transport and HTTPS connection.',
    pactTitle: 'Now connect all three: what happens after you type pact.me?',
    pactBody: 'You can now explain the core request path instead of saying “the browser sends a request to the server”. The important skill is naming the layers in order and knowing what job each one performs.',
    pactSteps: ['Browser parses https://pact.me and checks caches', 'DNS resolves pact.me to an IP address', 'Browser opens transport: TCP for HTTP/1.1 or HTTP/2, or QUIC over UDP for HTTP/3', 'TLS establishes a secure channel', 'Browser sends an HTTP request such as GET /', 'PACT infrastructure returns an HTTP response', 'Browser parses the response and may request more resources'],
    revision: {
      headline: 'Names first, connections second.',
      thinkWhen: ['You have a hostname but need a destination.', 'You see records, TTLs, nameservers or resolution failures.', 'You are explaining the first stages of a browser request.'],
      vocabulary: ['resolver', 'root', 'TLD', 'authoritative', 'A', 'AAAA', 'CNAME', 'TTL', 'cache'],
      mistakes: ['Saying the browser always queries root servers directly.', 'Saying root servers store every website’s IP.', 'Treating DNS resolution as connecting to the server.', 'Forgetting caches and TTLs.'],
      interviewQuestions: ['How does DNS work?', 'What happens when you type a URL and press Enter?', 'Recursive vs authoritative DNS?', 'What is TTL?', 'A vs AAAA vs CNAME?'],
      sentence: 'DNS turns a human-friendly name into usable records; only then can transport and HTTP begin.',
    },
  },
}

export const getSystemDesignModule = (id: string) => systemDesignModules[id]
