import type { ChoiceQuestion, CodeChallengeData } from '../../types'

export const patternQuestions: ChoiceQuestion[] = [
  {
    id: 'hash-pattern-1',
    prompt: 'Return true if any number appears more than once.',
    choices: ['Hash set', 'Binary search', 'Queue', 'Prefix sum'],
    answer: 'Hash set',
    signal: 'Have I seen this value before?',
    explanation: 'A set stores values already encountered and gives fast average membership checks.',
    tempting: 'Sorting can expose duplicates too, but it changes order and costs O(n log n).',
  },
  {
    id: 'hash-pattern-2',
    prompt: 'Count how many times each word appears in a paragraph.',
    choices: ['Hash map', 'Two pointers', 'Stack', 'Binary search'],
    answer: 'Hash map',
    signal: 'Frequency by key',
    explanation: 'Each word is a key and its count is the associated value.',
  },
  {
    id: 'hash-pattern-3',
    prompt: 'Find two values in an unsorted array that add to a target in expected O(n) time.',
    choices: ['Hash map / set', 'Two pointers without sorting', 'Queue', 'Prefix sum'],
    answer: 'Hash map / set',
    signal: 'Need fast lookup of the complement',
    explanation: 'For each value x, ask whether target - x has already been seen.',
    tempting: 'Two pointers is strongest when order, usually sorted order, tells you which pointer can safely move.',
  },
  {
    id: 'hash-pattern-4',
    prompt: 'Find a target in a sorted array.',
    choices: ['Binary search', 'Hash map', 'Stack', 'Queue'],
    answer: 'Binary search',
    signal: 'Sorted input + target lookup',
    explanation: 'The sorted order is stronger than generic fast lookup because it lets you discard half the search space without extra memory.',
  },
  {
    id: 'hash-pattern-5',
    prompt: 'Determine whether two strings are anagrams.',
    choices: ['Frequency map', 'Queue', 'Linked list', 'Prefix sum'],
    answer: 'Frequency map',
    signal: 'Same values with same counts',
    explanation: 'Character counts are exactly the information needed to compare the two strings.',
  },
]

export const predictionQuestions: ChoiceQuestion[] = [
  {
    id: 'hash-predict-1',
    prompt: 'const seen = new Set([2, 5]); seen.has(5) returns…',
    choices: ['true', 'false', '5', 'undefined'],
    answer: 'true',
    explanation: 'The set contains the value 5, so membership is true.',
  },
  {
    id: 'hash-predict-2',
    prompt: 'A Map stores information primarily as…',
    choices: ['key → value pairs', 'sorted positions only', 'last-in first-out items', 'parent → child edges only'],
    answer: 'key → value pairs',
    explanation: 'A map associates each key with a value such as a count, index, object, or state.',
  },
  {
    id: 'hash-predict-3',
    prompt: 'Average-case lookup in a well-behaved hash map is usually treated as…',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(1)',
    explanation: 'Interview analysis normally treats hash lookup, insert, and delete as constant average time.',
  },
  {
    id: 'hash-predict-4',
    prompt: 'If you only care whether a value exists, the simpler structure is usually…',
    choices: ['Set', 'Map from value to itself', 'Queue', 'Stack'],
    answer: 'Set',
    explanation: 'A set models membership directly. Use a map when you need associated information.',
  },
]

export const complexityQuestions: ChoiceQuestion[] = [
  {
    id: 'hash-complexity-1',
    prompt: 'Insert n distinct values into a hash set in one pass.',
    choices: ['O(1)', 'O(log n)', 'O(n) expected', 'O(n²) required'],
    answer: 'O(n) expected',
    explanation: 'There are n inserts, each treated as O(1) average time.',
  },
  {
    id: 'hash-complexity-2',
    prompt: 'Store up to n distinct values in a set. Extra space is…',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(n)',
    explanation: 'In the worst ordinary case, every input value is distinct and must be stored.',
  },
  {
    id: 'hash-complexity-3',
    prompt: 'Use nested loops to compare every pair for duplicates.',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(n²)',
    explanation: 'Each element can be compared with many others, producing pairwise work.',
  },
  {
    id: 'hash-complexity-4',
    prompt: 'Trade O(n) extra memory for O(n) expected time instead of O(n²) pair comparisons. What are you doing?',
    choices: ['Using a time-space trade-off', 'Making both time and space constant', 'Using recursion', 'Using binary search'],
    answer: 'Using a time-space trade-off',
    explanation: 'Hash structures often spend extra memory to remember information and avoid repeated scanning.',
  },
  {
    id: 'hash-complexity-5',
    prompt: 'Which operation is NOT guaranteed O(1) worst-case for a general hash map?',
    choices: ['Lookup', 'Insert', 'Delete', 'All of these can degrade in worst cases'],
    answer: 'All of these can degrade in worst cases',
    explanation: 'Hash maps are normally described as O(1) average/expected, not strict worst-case constant time.',
  },
]

export const mixedQuestions: ChoiceQuestion[] = [
  {
    id: 'hash-mixed-1',
    prompt: 'Return the first repeated email address in a stream of addresses.',
    choices: ['Hash set', 'Two pointers', 'Binary search', 'Prefix sum', 'Stack', 'Queue'],
    answer: 'Hash set',
    signal: 'Seen before?',
    explanation: 'Store each email as it appears; the first membership hit is the answer.',
  },
  {
    id: 'hash-mixed-2',
    prompt: 'Return the most common word in a list.',
    choices: ['Hash map', 'Two pointers', 'Sliding window', 'Binary search', 'Stack', 'Queue'],
    answer: 'Hash map',
    signal: 'Frequency by value',
    explanation: 'Count each word, then track or scan for the largest count.',
  },
  {
    id: 'hash-mixed-3',
    prompt: 'Find two values in a sorted array whose sum is a target with O(1) extra space.',
    choices: ['Two pointers', 'Hash map', 'Stack', 'Queue', 'Prefix sum', 'Sliding window'],
    answer: 'Two pointers',
    signal: 'Sorted + pair + O(1) space',
    explanation: 'Sorted order tells you which end can move inward, so a map is unnecessary.',
  },
  {
    id: 'hash-mixed-4',
    prompt: 'Find the longest substring with no repeated characters.',
    choices: ['Sliding window + set/map', 'Hash map alone without boundaries', 'Binary search', 'Stack', 'Queue', 'Sorting'],
    answer: 'Sliding window + set/map',
    signal: 'Longest contiguous range + membership constraint',
    explanation: 'The set/map tracks what is inside the current window, while the window controls the substring boundaries.',
  },
  {
    id: 'hash-mixed-5',
    prompt: 'Answer 100,000 range-sum queries on the same array.',
    choices: ['Prefix sum', 'Hash map', 'Two pointers', 'Stack', 'Queue', 'Binary search'],
    answer: 'Prefix sum',
    signal: 'Many repeated range queries',
    explanation: 'Precompute cumulative sums once, then answer each range quickly.',
  },
  {
    id: 'hash-mixed-6',
    prompt: 'Check whether every opening bracket has the correct most-recent closing partner.',
    choices: ['Stack', 'Hash set', 'Two pointers', 'Binary search', 'Queue', 'Prefix sum'],
    answer: 'Stack',
    signal: 'Most recent unmatched item',
    explanation: 'Nested bracket matching is last-in, first-out.',
  },
  {
    id: 'hash-mixed-7',
    prompt: 'Find the index of target 42 in a sorted list of unique numbers.',
    choices: ['Binary search', 'Hash map', 'Sliding window', 'Stack', 'Queue', 'Prefix sum'],
    answer: 'Binary search',
    signal: 'Sorted + exact target',
    explanation: 'No extra structure is needed; sorted order gives logarithmic search.',
  },
]

export const challenges: CodeChallengeData[] = [
  {
    id: 'hash-guided-has-duplicate',
    eyebrow: 'Guided challenge',
    title: 'Contains a duplicate?',
    difficulty: 'Guided',
    description: 'Return true if any number appears at least twice. Aim for expected O(n) time.',
    examples: ['hasDuplicate([1, 2, 3, 2]) → true', 'hasDuplicate([1, 2, 3]) → false'],
    constraints: ['0 ≤ nums.length ≤ 100,000', 'Numbers may be negative'],
    starter: `function hasDuplicate(nums: number[]): boolean {\n  // What information would stop you rescanning earlier values?\n  return false;\n}`,
    functionName: 'hasDuplicate',
    tests: [
      { label: 'duplicate', args: [[1, 2, 3, 2]], expected: true },
      { label: 'unique', args: [[1, 2, 3]], expected: false },
      { label: 'empty', args: [[]], expected: false },
      { label: 'negative duplicate', args: [[-1, 4, -1]], expected: true },
    ],
    hints: [
      'As you scan, ask: have I seen this number before?',
      'A Set is designed for membership.',
      'Check before adding. If the value is already present, return true immediately.',
    ],
    solution: `function hasDuplicate(nums: number[]): boolean {\n  const seen = new Set<number>();\n\n  for (const num of nums) {\n    if (seen.has(num)) return true;\n    seen.add(num);\n  }\n\n  return false;\n}`,
    solutionExplanation: 'The set remembers all earlier values, so every new value needs only one average O(1) membership check.',
    time: 'O(n)',
    space: 'O(n)',
    remember: '“Have I seen this before?” is one of the strongest hash-set signals.',
  },
  {
    id: 'hash-independent-first-repeated',
    eyebrow: 'Independent 1',
    title: 'First repeated value',
    difficulty: 'Independent',
    description: 'Return the first value whose second occurrence is encountered while scanning left to right. Return null if there is no repeat.',
    examples: ['firstRepeated([4, 2, 7, 2, 4]) → 2'],
    constraints: ['0 ≤ nums.length ≤ 100,000'],
    starter: `function firstRepeated(nums: number[]): number | null {\n  // Your solution\n  return null;\n}`,
    functionName: 'firstRepeated',
    tests: [
      { label: 'first repeat by scan order', args: [[4, 2, 7, 2, 4]], expected: 2 },
      { label: 'no repeat', args: [[1, 2, 3]], expected: null },
      { label: 'immediate repeat', args: [[5, 5, 1]], expected: 5 },
      { label: 'empty', args: [[]], expected: null },
    ],
    hints: [
      'The phrase “first repeated while scanning” means you should preserve scan order.',
      'Do not sort; sorting would change the order information.',
      'Return as soon as the current value is already in the set.',
    ],
    solution: `function firstRepeated(nums: number[]): number | null {\n  const seen = new Set<number>();\n\n  for (const num of nums) {\n    if (seen.has(num)) return num;\n    seen.add(num);\n  }\n\n  return null;\n}`,
    solutionExplanation: 'The set answers membership while the loop preserves the original encounter order.',
    time: 'O(n)',
    space: 'O(n)',
    remember: 'Hashing is especially useful when you need fast memory without losing the original scan order.',
  },
  {
    id: 'hash-independent-two-sum',
    eyebrow: 'Independent 2',
    title: 'Two Sum indices',
    difficulty: 'Independent',
    description: 'Return the indices of two different values whose sum equals target. Exactly one valid answer exists.',
    examples: ['twoSum([2, 7, 11, 15], 9) → [0, 1]'],
    constraints: ['2 ≤ nums.length ≤ 100,000', 'Exactly one valid pair exists', 'Return the earlier stored index first'],
    starter: `function twoSum(nums: number[], target: number): number[] {\n  // Your solution\n  return [];\n}`,
    functionName: 'twoSum',
    tests: [
      { label: 'classic', args: [[2, 7, 11, 15], 9], expected: [0, 1] },
      { label: 'middle pair', args: [[3, 2, 4], 6], expected: [1, 2] },
      { label: 'duplicate values', args: [[3, 3], 6], expected: [0, 1] },
      { label: 'negative', args: [[-3, 4, 3, 90], 0], expected: [0, 2] },
    ],
    hints: [
      'At nums[i], the missing value is target - nums[i].',
      'Store value → index for values you have already passed.',
      'Check for the complement before storing the current value so you never use one element twice.',
    ],
    solution: `function twoSum(nums: number[], target: number): number[] {\n  const indexByValue = new Map<number, number>();\n\n  for (let i = 0; i < nums.length; i++) {\n    const need = target - nums[i];\n    if (indexByValue.has(need)) return [indexByValue.get(need)!, i];\n    indexByValue.set(nums[i], i);\n  }\n\n  return [];\n}`,
    solutionExplanation: 'The map turns “search all earlier values for my complement” into one expected constant-time lookup.',
    time: 'O(n)',
    space: 'O(n)',
    remember: 'When you need a partner/complement in unsorted data, ask whether a hash map can remember what you have already seen.',
  },
]
