import type { ChoiceQuestion, CodeChallengeData } from '../../types'

export const patternQuestions: ChoiceQuestion[] = [
  {
    id: 'strings-pattern-1',
    prompt: 'Count how many uppercase letters appear in a username.',
    choices: ['String scan', 'Binary search', 'Queue', 'Prefix sum'],
    answer: 'String scan',
    signal: 'Inspect every character once',
    explanation: 'Each character may affect the count, so a direct left-to-right scan is the simplest useful approach.',
    tempting: 'Binary search needs ordered search space. Character positions here do not let you discard half the string.',
  },
  {
    id: 'strings-pattern-2',
    prompt: 'Find the longest substring with no repeated characters.',
    choices: ['Sliding window + set/map', 'Plain string scan only', 'Stack', 'Sorting'],
    answer: 'Sliding window + set/map',
    signal: 'Longest + substring + changing contiguous range',
    explanation: 'The answer is a contiguous range whose boundary changes as repeated characters enter. Sliding window is the key pattern.',
    tempting: 'A plain scan sees characters, but does not by itself maintain the best valid substring efficiently.',
  },
  {
    id: 'strings-pattern-3',
    prompt: 'Check whether two strings contain the same character frequencies.',
    choices: ['Hash map / frequency counting', 'Queue', 'Binary search', 'Prefix sum'],
    answer: 'Hash map / frequency counting',
    signal: 'Compare counts of characters',
    explanation: 'Frequency is the clue. A map or fixed-size count array records how often each character appears.',
    tempting: 'Sorting can also work, but frequency counting often avoids the O(n log n) sort.',
  },
  {
    id: 'strings-pattern-4',
    prompt: 'Check whether a cleaned string reads the same forwards and backwards.',
    choices: ['Two pointers', 'Hash set', 'Queue', 'Prefix sum'],
    answer: 'Two pointers',
    signal: 'Compare mirrored positions',
    explanation: 'One pointer starts at each end. Matching characters move both pointers inward.',
    tempting: 'Reversing the string works, but uses extra space and misses the stronger mirrored-comparison clue.',
  },
  {
    id: 'strings-pattern-5',
    prompt: 'Split "name=Indi&role=founder" into key/value pieces.',
    choices: ['String parsing', 'Binary search', 'Stack', 'Linked list'],
    answer: 'String parsing',
    signal: 'Delimiters define structure',
    explanation: 'Characters such as = and & act as boundaries. The core task is scanning and extracting pieces based on delimiters.',
  },
]

export const predictionQuestions: ChoiceQuestion[] = [
  {
    id: 'strings-predict-1',
    prompt: '"pattern"[0] evaluates to…',
    choices: ['p', 'a', 'pattern', 'undefined'],
    answer: 'p',
    explanation: 'String indexing is zero-based, so index 0 is the first character.',
  },
  {
    id: 'strings-predict-2',
    prompt: '"abc".length is…',
    choices: ['2', '3', '4', 'undefined'],
    answer: '3',
    explanation: 'The string has three characters.',
  },
  {
    id: 'strings-predict-3',
    prompt: 'If s = "cat", assigning s[0] = "b" in JavaScript changes s to "bat".',
    choices: ['True', 'False'],
    answer: 'False',
    explanation: 'JavaScript strings are immutable. You create a new string rather than changing one character in place.',
  },
  {
    id: 'strings-predict-4',
    prompt: 'Scanning every character of a length-n string once is…',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(n)',
    explanation: 'The amount of work grows linearly with the number of characters.',
  },
]

export const complexityQuestions: ChoiceQuestion[] = [
  {
    id: 'strings-complexity-1',
    prompt: 'Read s[i] when i is a known valid index.',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(1)',
    explanation: 'Indexed character access is constant time in the usual model used for interview problems.',
  },
  {
    id: 'strings-complexity-2',
    prompt: 'Count vowels by visiting each character once.',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 'O(n)',
    explanation: 'Every character may need to be checked.',
  },
  {
    id: 'strings-complexity-3',
    prompt: 'Build a reversed copy of a length-n string.',
    choices: ['O(1) space', 'O(log n) space', 'O(n) space', 'O(n²) space'],
    answer: 'O(n) space',
    explanation: 'The new string contains n characters, so the output itself requires linear space.',
  },
  {
    id: 'strings-complexity-4',
    prompt: 'Compare every substring against every other substring in a naive solution. Which warning sign is most likely?',
    choices: ['Constant work', 'Linear work', 'Quadratic or worse work', 'Logarithmic work'],
    answer: 'Quadratic or worse work',
    explanation: 'Generating or comparing many pairs of ranges often creates nested work that grows quickly.',
  },
  {
    id: 'strings-complexity-5',
    prompt: 'Which is usually better for a simple character count?',
    choices: ['One O(n) scan', 'Sort first O(n log n)', 'Nested loops O(n²)', 'They are identical'],
    answer: 'One O(n) scan',
    explanation: 'Counting a property of each character needs only one pass; sorting adds unnecessary work.',
  },
]

export const mixedQuestions: ChoiceQuestion[] = [
  {
    id: 'strings-mixed-1',
    prompt: 'Return the first character that appears twice while scanning left to right.',
    choices: ['String scan only', 'Hash set', 'Two pointers', 'Sliding window', 'Binary search', 'Stack'],
    answer: 'Hash set',
    signal: 'Seen before? membership lookup',
    explanation: 'A set remembers characters already encountered and checks membership quickly.',
  },
  {
    id: 'strings-mixed-2',
    prompt: 'Check whether "racecar" is a palindrome without creating a reversed copy.',
    choices: ['Two pointers', 'Hash map', 'Sliding window', 'Sorting', 'Queue', 'Prefix sum'],
    answer: 'Two pointers',
    signal: 'Compare opposite ends',
    explanation: 'Move inward from both ends while corresponding characters match.',
  },
  {
    id: 'strings-mixed-3',
    prompt: 'Find the longest substring containing at most two distinct characters.',
    choices: ['Sliding window', 'Binary search', 'Stack', 'Sorting', 'Plain traversal only', 'Queue'],
    answer: 'Sliding window',
    signal: 'Longest + contiguous substring + constraint',
    explanation: 'Maintain a window and shrink it whenever it contains more than two distinct characters.',
  },
  {
    id: 'strings-mixed-4',
    prompt: 'Count how many digits appear in a product code.',
    choices: ['String scan', 'Two pointers', 'Hash map', 'Binary search', 'Stack', 'Sorting'],
    answer: 'String scan',
    signal: 'Apply one test to every character',
    explanation: 'A single traversal with a counter is enough.',
  },
  {
    id: 'strings-mixed-5',
    prompt: 'Determine whether two words are anagrams in linear expected time.',
    choices: ['Frequency map', 'Queue', 'Binary search', 'Prefix sum', 'Linked list', 'Recursion'],
    answer: 'Frequency map',
    signal: 'Same characters with same counts',
    explanation: 'Count characters in one word and subtract or compare counts from the other.',
  },
  {
    id: 'strings-mixed-6',
    prompt: 'Parse a CSV-like line and extract fields separated by commas.',
    choices: ['String parsing', 'Binary search', 'Two pointers only', 'Heap', 'Graph traversal', 'Prefix sum'],
    answer: 'String parsing',
    signal: 'Delimiter defines boundaries',
    explanation: 'Scan for separators and build or extract each field.',
  },
  {
    id: 'strings-mixed-7',
    prompt: 'Find whether a target word exists in an alphabetically sorted array of words.',
    choices: ['Binary search', 'String scan', 'Sliding window', 'Stack', 'Queue', 'Prefix sum'],
    answer: 'Binary search',
    signal: 'Sorted collection + target lookup',
    explanation: 'The important structure is the sorted array, not the fact that each element happens to be a string.',
  },
]

export const challenges: CodeChallengeData[] = [
  {
    id: 'strings-guided-count-vowels',
    eyebrow: 'Guided challenge',
    title: 'Count the vowels',
    difficulty: 'Guided',
    description: 'Return the number of vowels in a string. Treat a, e, i, o and u as vowels and ignore case.',
    examples: ['countVowels("Pattern Lab") → 3', 'countVowels("rhythm") → 0'],
    constraints: ['0 ≤ s.length ≤ 100,000', 'Input contains ordinary Unicode text; tests use English letters and spaces'],
    starter: `function countVowels(s: string): number {\n  // One pass. What tiny piece of state do you need?\n  return 0;\n}`,
    functionName: 'countVowels',
    tests: [
      { label: 'mixed case', args: ['Pattern Lab'], expected: 3 },
      { label: 'no vowels', args: ['rhythm'], expected: 0 },
      { label: 'all vowels', args: ['AEIOU'], expected: 5 },
      { label: 'empty', args: [''], expected: 0 },
    ],
    hints: [
      'You need to inspect each character once.',
      'Convert each character to lowercase, then test membership in "aeiou".',
      'Keep a counter and increment it when the current character is a vowel.',
    ],
    solution: `function countVowels(s: string): number {\n  let count = 0;\n  const vowels = new Set(['a', 'e', 'i', 'o', 'u']);\n\n  for (const char of s.toLowerCase()) {\n    if (vowels.has(char)) count++;\n  }\n\n  return count;\n}`,
    solutionExplanation: 'The solution scans once and keeps only a counter plus a constant-size vowel set.',
    time: 'O(n)',
    space: 'O(1)',
    remember: 'When the question asks for a property of every character, start with one clean string scan.',
  },
  {
    id: 'strings-independent-reverse-words',
    eyebrow: 'Independent 1',
    title: 'Reverse the word order',
    difficulty: 'Independent',
    description: 'Given a sentence with words separated by single spaces, return a new sentence with the word order reversed.',
    examples: ['reverseWords("build pattern instincts") → "instincts pattern build"'],
    constraints: ['0 ≤ s.length ≤ 100,000', 'Words are separated by exactly one space', 'Do not reverse the letters inside each word'],
    starter: `function reverseWords(s: string): string {\n  // Your solution\n  return '';\n}`,
    functionName: 'reverseWords',
    tests: [
      { label: 'three words', args: ['build pattern instincts'], expected: 'instincts pattern build' },
      { label: 'one word', args: ['hello'], expected: 'hello' },
      { label: 'empty', args: [''], expected: '' },
      { label: 'two words', args: ['data structures'], expected: 'structures data' },
    ],
    hints: [
      'The delimiter is a space, so think split → rearrange → join.',
      'The output must be a new string because strings are immutable.',
      'An array of words is a natural temporary representation here.',
    ],
    solution: `function reverseWords(s: string): string {\n  if (s.length === 0) return '';\n  return s.split(' ').reverse().join(' ');\n}`,
    solutionExplanation: 'Splitting exposes the word boundaries, reversing changes word order, and joining constructs the new string.',
    time: 'O(n)',
    space: 'O(n)',
    remember: 'For parsing problems, identify the delimiter and choose a representation that makes the transformation obvious.',
  },
  {
    id: 'strings-independent-longest-word',
    eyebrow: 'Independent 2',
    title: 'Find the longest word',
    difficulty: 'Independent',
    description: 'Return the longest word in a sentence whose words are separated by single spaces. If there is a tie, return the first longest word.',
    examples: ['longestWord("learn patterns not tricks") → "patterns"'],
    constraints: ['1 ≤ s.length ≤ 100,000', 'At least one non-empty word is present'],
    starter: `function longestWord(s: string): string {\n  // Your solution\n  return '';\n}`,
    functionName: 'longestWord',
    tests: [
      { label: 'basic', args: ['learn patterns not tricks'], expected: 'patterns' },
      { label: 'tie keeps first', args: ['code data'], expected: 'code' },
      { label: 'single', args: ['algorithm'], expected: 'algorithm' },
      { label: 'mixed lengths', args: ['a three seven'], expected: 'three' },
    ],
    hints: [
      'Split the sentence into words, then scan once.',
      'Keep the best word seen so far.',
      'Use > rather than >= if ties should keep the first word.',
    ],
    solution: `function longestWord(s: string): string {\n  const words = s.split(' ');\n  let best = words[0];\n\n  for (let i = 1; i < words.length; i++) {\n    if (words[i].length > best.length) best = words[i];\n  }\n\n  return best;\n}`,
    solutionExplanation: 'After parsing the words, the rest is a standard one-pass running-best pattern.',
    time: 'O(n)',
    space: 'O(n)',
    remember: 'String problems often become simpler once you expose the right units: characters, words, or substrings.',
  },
]
