import type { ChoiceQuestion, CodeChallengeData } from '../../types'

export const patternQuestions: ChoiceQuestion[] = [
  {
    id: 'sliding-window-pattern-1',
    prompt: 'Find the maximum sum of any 4 consecutive numbers in an array.',
    choices: ['Fixed sliding window', 'Hash map', 'Binary search', 'Stack'],
    answer: 'Fixed sliding window',
    signal: 'Contiguous + exactly k elements',
    explanation: 'Keep a running sum of four adjacent values. When the window moves, subtract the outgoing value and add the incoming one.',
    tempting: 'Nested loops work, but they recompute almost the same sum for every overlapping block.',
  },
  {
    id: 'sliding-window-pattern-2',
    prompt: 'Find the longest substring containing no repeated characters.',
    choices: ['Variable sliding window', 'Opposite-end two pointers', 'Prefix sum', 'Sorting'],
    answer: 'Variable sliding window',
    signal: 'Longest contiguous range + dynamic validity rule',
    explanation: 'Expand the right edge while characters are unique. When a duplicate makes the window invalid, move the left edge until uniqueness is restored.',
  },
  {
    id: 'sliding-window-pattern-3',
    prompt: 'Answer 50,000 queries asking for the sum between indices left and right in the same array.',
    choices: ['Prefix sums', 'Sliding window', 'Stack', 'Two pointers'],
    answer: 'Prefix sums',
    signal: 'Many independent range-sum queries',
    explanation: 'A prefix-sum array lets each arbitrary range sum be answered in O(1) after O(n) preprocessing. There is no single window moving progressively through the queries.',
  },
  {
    id: 'sliding-window-pattern-4',
    prompt: 'Find two numbers in a sorted array whose sum equals target.',
    choices: ['Two pointers', 'Sliding window', 'Queue', 'Prefix sum'],
    answer: 'Two pointers',
    signal: 'Sorted + pair, not a contiguous range',
    explanation: 'The chosen pair can come from far-apart positions and does not represent every element between them, so this is elimination with two pointers rather than a window.',
  },
  {
    id: 'sliding-window-pattern-5',
    prompt: 'Find the shortest contiguous subarray of positive numbers whose sum is at least target.',
    choices: ['Variable sliding window', 'Hash set', 'Stack', 'Sorting'],
    answer: 'Variable sliding window',
    signal: 'Shortest contiguous range + positive values + threshold',
    explanation: 'Positive values make the condition behave predictably: expand until the sum is large enough, then shrink from the left while it remains valid.',
  },
  {
    id: 'sliding-window-pattern-6',
    prompt: 'Choose any 3 values from an array to maximise their sum; the values do not need to be adjacent.',
    choices: ['Sorting / top-k reasoning', 'Sliding window', 'Prefix sum', 'Queue'],
    answer: 'Sorting / top-k reasoning',
    signal: 'Arbitrary choices, not contiguous',
    explanation: 'Sliding window only represents adjacent elements. If the selected values can skip positions, the core structural requirement is missing.',
  },
]

export const predictionQuestions: ChoiceQuestion[] = [
  {
    id: 'sliding-window-predict-1',
    prompt: 'nums = [2, 1, 5, 1, 3], k = 3. The first window sum is…',
    choices: ['3', '7', '8', '9'],
    answer: '8',
    explanation: 'The first window is [2, 1, 5], so 2 + 1 + 5 = 8.',
  },
  {
    id: 'sliding-window-predict-2',
    prompt: 'Move the size-3 window [2, 1, 5] one step right in [2, 1, 5, 1, 3]. What update gives the new sum?',
    choices: ['8 - 2 + 1', '8 + 2 + 1', '8 - 5 + 3', 'Recompute everything only'],
    answer: '8 - 2 + 1',
    explanation: 'The value 2 leaves from the left and the next value 1 enters from the right, giving the new window [1, 5, 1] with sum 7.',
  },
  {
    id: 'sliding-window-predict-3',
    prompt: 'In a variable window, the right edge makes the window invalid. What usually happens next?',
    choices: ['Move left until validity is restored', 'Reset both pointers to zero', 'Sort the window', 'Move right backwards'],
    answer: 'Move left until validity is restored',
    explanation: 'The right edge discovers new candidates; the left edge repairs the window when the invariant is broken.',
  },
  {
    id: 'sliding-window-predict-4',
    prompt: 'Why can a variable sliding window with an inner while-loop still be O(n)?',
    choices: ['Each boundary moves forward at most n times', 'The while-loop never runs', 'Hash maps are always O(1) total', 'Only one element is inspected'],
    answer: 'Each boundary moves forward at most n times',
    explanation: 'Across the whole algorithm, right advances at most n times and left advances at most n times. The movements add rather than multiply.',
  },
  {
    id: 'sliding-window-predict-5',
    prompt: 'For longest substring without repeats, when should you update the best length?',
    choices: ['After the window is valid', 'Only before adding a character', 'Only when the whole string is processed', 'Before removing duplicates'],
    answer: 'After the window is valid',
    explanation: 'The answer should be measured on a range that satisfies the no-duplicates invariant.',
  },
]

export const complexityQuestions: ChoiceQuestion[] = [
  {
    id: 'sliding-window-complexity-1',
    prompt: 'Maximum sum of every length-k contiguous subarray using a running sum takes…',
    choices: ['O(1)', 'O(log n)', 'O(n)', 'O(nk)'],
    answer: 'O(n)',
    explanation: 'Build the first sum once, then each slide performs constant work: one subtraction and one addition.',
  },
  {
    id: 'sliding-window-complexity-2',
    prompt: 'A variable window moves right from 0 to n-1 while left only moves forward. Total pointer movement is…',
    choices: ['O(n)', 'O(n²)', 'O(log n)', 'O(1)'],
    answer: 'O(n)',
    explanation: 'Each index can be entered by right and removed by left at most once.',
  },
  {
    id: 'sliding-window-complexity-3',
    prompt: 'A fixed-window running sum stores left/right positions and one sum. Extra space is…',
    choices: ['O(1)', 'O(k)', 'O(n)', 'O(n²)'],
    answer: 'O(1)',
    explanation: 'The amount of stored state does not grow with the input or window length.',
  },
  {
    id: 'sliding-window-complexity-4',
    prompt: 'Longest substring without repeated characters using a set may need extra space up to…',
    choices: ['O(k) / O(distinct values in the window)', 'Always O(1)', 'O(n²)', 'O(log n) only'],
    answer: 'O(k) / O(distinct values in the window)',
    explanation: 'The set stores characters currently represented by the window, bounded by the number of distinct values it contains.',
  },
  {
    id: 'sliding-window-complexity-5',
    prompt: 'Checking every contiguous start/end pair and recomputing each range can reach…',
    choices: ['O(n²) or worse', 'O(1)', 'O(log n)', 'Always O(n)'],
    answer: 'O(n²) or worse',
    explanation: 'There are quadratically many contiguous ranges. Sliding window wins when the constraint lets you avoid exploring them independently.',
  },
]

export const mixedQuestions: ChoiceQuestion[] = [
  {
    id: 'sliding-window-mixed-1',
    prompt: 'Find the highest average score across any 7 consecutive days.',
    choices: ['Fixed sliding window', 'Prefix sum only', 'Hash map', 'Binary search', 'Stack', 'Two pointers'],
    answer: 'Fixed sliding window',
    signal: 'Exactly 7 consecutive values',
    explanation: 'Maintain the sum of the current seven-day block and slide it one day at a time.',
  },
  {
    id: 'sliding-window-mixed-2',
    prompt: 'Find the longest substring containing at most 2 distinct characters.',
    choices: ['Variable sliding window + frequency map', 'Opposite-end two pointers', 'Stack', 'Binary search', 'Sorting', 'Prefix sum'],
    answer: 'Variable sliding window + frequency map',
    signal: 'Longest contiguous range + at most k distinct',
    explanation: 'Expand right, count characters, and shrink left while the distinct count exceeds two.',
  },
  {
    id: 'sliding-window-mixed-3',
    prompt: 'Given a sorted array, find a pair that sums to 40.',
    choices: ['Two pointers', 'Sliding window', 'Prefix sum', 'Stack', 'Queue', 'Sorting'],
    answer: 'Two pointers',
    signal: 'Pair from sorted input',
    explanation: 'A pair problem is not asking about every element inside one contiguous range.',
  },
  {
    id: 'sliding-window-mixed-4',
    prompt: 'After preprocessing, repeatedly return sum(nums[l...r]) for arbitrary l and r.',
    choices: ['Prefix sums', 'Sliding window', 'Hash set', 'Stack', 'Queue', 'Two pointers'],
    answer: 'Prefix sums',
    signal: 'Many arbitrary range queries',
    explanation: 'Prefix sums turn each independent range query into a subtraction of two cumulative totals.',
  },
  {
    id: 'sliding-window-mixed-5',
    prompt: 'Find the shortest contiguous positive-number subarray with sum at least 100.',
    choices: ['Variable sliding window', 'Stack', 'Hash set', 'Sorting', 'Two pointers opposite ends', 'Queue'],
    answer: 'Variable sliding window',
    signal: 'Shortest contiguous + threshold + positive values',
    explanation: 'Expand to reach the threshold, then repeatedly shrink to find the smallest still-valid range.',
  },
  {
    id: 'sliding-window-mixed-6',
    prompt: 'Determine whether any value appears twice anywhere in an unsorted array.',
    choices: ['Hash set', 'Sliding window', 'Prefix sum', 'Binary search', 'Queue', 'Two pointers'],
    answer: 'Hash set',
    signal: 'Global membership, no contiguous range requirement',
    explanation: 'You need to remember values seen anywhere, not maintain one adjacent region.',
  },
  {
    id: 'sliding-window-mixed-7',
    prompt: 'Find a contiguous subarray whose exact sum equals k when the array may contain positive and negative numbers.',
    choices: ['Prefix sum + hash map', 'Positive-number sliding window', 'Opposite-end two pointers', 'Stack', 'Sorting', 'Queue'],
    answer: 'Prefix sum + hash map',
    signal: 'Exact sum + negative values break simple shrink/expand monotonicity',
    explanation: 'With negative values, adding an item can reduce the sum and removing one can increase it, so the usual threshold-based sliding-window movement is no longer reliable. Prefix sums with a map handle this.',
  },
  {
    id: 'sliding-window-mixed-8',
    prompt: 'Find the maximum value in every contiguous window of size k for a huge array.',
    choices: ['Monotonic deque window', 'Re-sort every window', 'Binary search once', 'Hash set', 'Prefix sum', 'Opposite-end pointers'],
    answer: 'Monotonic deque window',
    signal: 'Every fixed-size window + need max, not an additive statistic',
    explanation: 'This is still a window problem, but a running sum is not enough. A monotonic deque keeps only useful maximum candidates as the window moves.',
  },
]

export const challenges: CodeChallengeData[] = [
  {
    id: 'sliding-window-guided-max-sum-k',
    eyebrow: 'Guided challenge',
    title: 'Maximum sum of a size-k window',
    difficulty: 'Guided',
    description: 'Given an array and a valid window size k, return the maximum sum of any k consecutive values.',
    examples: ['maxWindowSum([2, 1, 5, 1, 3, 2], 3) → 9', 'maxWindowSum([1, 9, -1, -2, 7, 3, -1, 2], 4) → 13'],
    constraints: ['1 ≤ k ≤ nums.length ≤ 100,000', 'Values may be positive, zero, or negative'],
    starter: `function maxWindowSum(nums: number[], k: number): number {\n  // 1. Build the first window sum.\n  // 2. Slide by subtracting the outgoing value and adding the incoming value.\n  return 0;\n}`,
    functionName: 'maxWindowSum',
    tests: [
      { label: 'classic window', args: [[2, 1, 5, 1, 3, 2], 3], expected: 9 },
      { label: 'mixed values', args: [[1, 9, -1, -2, 7, 3, -1, 2], 4], expected: 13 },
      { label: 'all negative', args: [[-4, -2, -7], 2], expected: -6 },
      { label: 'whole array', args: [[3, 4, 5], 3], expected: 12 },
    ],
    hints: [
      'Compute nums[0] through nums[k - 1] once.',
      'When right reaches k, nums[right] enters while nums[right - k] leaves.',
      'Track the best sum after every slide. Do not initialise best to 0 because all values might be negative.',
    ],
    solution: `function maxWindowSum(nums: number[], k: number): number {\n  let windowSum = 0;\n  for (let i = 0; i < k; i++) windowSum += nums[i];\n\n  let best = windowSum;\n  for (let right = k; right < nums.length; right++) {\n    windowSum += nums[right];\n    windowSum -= nums[right - k];\n    best = Math.max(best, windowSum);\n  }\n\n  return best;\n}`,
    solutionExplanation: 'Adjacent size-k windows overlap in k - 1 positions. Reuse the previous sum and update only the two values that changed.',
    time: 'O(n)',
    space: 'O(1)',
    remember: 'Fixed window = keep the width constant and update the state at the two edges.',
  },
  {
    id: 'sliding-window-independent-longest-unique',
    eyebrow: 'Independent 1',
    title: 'Longest substring without repeats',
    difficulty: 'Independent',
    description: 'Return the length of the longest contiguous substring containing no repeated characters.',
    examples: ['longestUniqueSubstringLength("abcabcbb") → 3', 'longestUniqueSubstringLength("pwwkew") → 3'],
    constraints: ['0 ≤ s.length ≤ 100,000', 'Treat characters exactly as they appear'],
    starter: `function longestUniqueSubstringLength(s: string): number {\n  // What state tells you whether the current window is valid?\n  return 0;\n}`,
    functionName: 'longestUniqueSubstringLength',
    tests: [
      { label: 'repeating pattern', args: ['abcabcbb'], expected: 3 },
      { label: 'one repeated char', args: ['bbbbb'], expected: 1 },
      { label: 'overlapping repeat', args: ['pwwkew'], expected: 3 },
      { label: 'empty', args: [''], expected: 0 },
    ],
    hints: [
      'Use a set to represent the characters currently inside the window.',
      'Before adding s[right], if it is already present, repeatedly remove s[left] and advance left.',
      'Once the window is valid, its length is right - left + 1.',
    ],
    solution: `function longestUniqueSubstringLength(s: string): number {\n  const seen = new Set<string>();\n  let left = 0;\n  let best = 0;\n\n  for (let right = 0; right < s.length; right++) {\n    while (seen.has(s[right])) {\n      seen.delete(s[left]);\n      left++;\n    }\n\n    seen.add(s[right]);\n    best = Math.max(best, right - left + 1);\n  }\n\n  return best;\n}`,
    solutionExplanation: 'Right expands the candidate range. A duplicate breaks the invariant, so left removes characters until the range is unique again. Every character enters and leaves the set at most once.',
    time: 'O(n)',
    space: 'O(k)',
    remember: 'Variable window = expand to discover, shrink to repair, measure only when the invariant is valid.',
  },
  {
    id: 'sliding-window-independent-min-length',
    eyebrow: 'Independent 2',
    title: 'Minimum-size subarray sum',
    difficulty: 'Independent',
    description: 'Given positive integers and a target, return the minimum length of a contiguous subarray whose sum is at least target. Return 0 if none exists.',
    examples: ['minSubarrayLen(7, [2, 3, 1, 2, 4, 3]) → 2', 'minSubarrayLen(11, [1, 1, 1, 1, 1, 1, 1, 1]) → 0'],
    constraints: ['1 ≤ nums.length ≤ 100,000', 'All nums[i] are positive integers', 'target > 0'],
    starter: `function minSubarrayLen(target: number, nums: number[]): number {\n  // Expand until valid. Then ask: can the window become smaller and stay valid?\n  return 0;\n}`,
    functionName: 'minSubarrayLen',
    tests: [
      { label: 'classic', args: [7, [2, 3, 1, 2, 4, 3]], expected: 2 },
      { label: 'single value', args: [4, [1, 4, 4]], expected: 1 },
      { label: 'no valid window', args: [11, [1, 1, 1, 1, 1, 1, 1, 1]], expected: 0 },
      { label: 'whole array needed', args: [15, [1, 2, 3, 4, 5]], expected: 5 },
    ],
    hints: [
      'Keep a running sum and expand right.',
      'Whenever sum >= target, record the current length and keep moving left while the condition still holds.',
      'Positive numbers are important: removing from the left can only reduce the sum, which makes this movement rule safe.',
    ],
    solution: `function minSubarrayLen(target: number, nums: number[]): number {\n  let left = 0;\n  let sum = 0;\n  let best = Infinity;\n\n  for (let right = 0; right < nums.length; right++) {\n    sum += nums[right];\n\n    while (sum >= target) {\n      best = Math.min(best, right - left + 1);\n      sum -= nums[left];\n      left++;\n    }\n  }\n\n  return best === Infinity ? 0 : best;\n}`,
    solutionExplanation: 'Because all numbers are positive, expanding cannot decrease the sum and shrinking cannot increase it. That monotonic behaviour lets the two boundaries safely search for the smallest valid range.',
    time: 'O(n)',
    space: 'O(1)',
    remember: 'For shortest-valid-window problems, keep shrinking while valid rather than stopping after one left move.',
  },
]
